name: Testing Clean Architecture Go
on:
  push:
    branches:
      - master
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Clean Architecture Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
    - run: go test -v -cover ./...